//! SST OpenCode adapter.
//!
//! Manifest: `AGENTS.md`
//! MCP: `.opencode.json` `mcpServers`
//! Hooks: `.opencode/plugins/*.ts` (file.edited, session.created, tool.execute.before/after).

use std::path::PathBuf;

use crate::error::CliResult;
use crate::platforms::{
    AdapterContext, InstallScope, McpFormat, Platform, PlatformAdapter,
};

#[derive(Debug, Clone, Copy, Default)]
pub struct OpenCode;

impl PlatformAdapter for OpenCode {
    fn platform(&self) -> Platform {
        Platform::OpenCode
    }

    fn detect(&self, ctx: &AdapterContext) -> bool {
        ctx.project_root.join(".opencode.json").exists()
            || ctx.project_root.join(".opencode").exists()
            || ctx.home.join(".opencode").exists()
    }

    fn manifest_path(&self, ctx: &AdapterContext) -> PathBuf {
        match ctx.scope {
            InstallScope::Project => ctx.project_root.join("AGENTS.md"),
            InstallScope::User | InstallScope::Global => ctx.home.join("AGENTS.md"),
        }
    }

    fn mcp_config_path(&self, ctx: &AdapterContext) -> PathBuf {
        match ctx.scope {
            InstallScope::Project => ctx.project_root.join(".opencode.json"),
            InstallScope::User | InstallScope::Global => ctx.home.join(".opencode.json"),
        }
    }

    fn mcp_format(&self) -> McpFormat {
        McpFormat::JsonObject
    }

    /// Drop a TypeScript plugin stub that wires OpenCode's hook events to
    /// the `datatree` CLI. We use `execFile` (no shell) with array args so
    /// the user's tool/session strings can never be interpreted as shell
    /// metacharacters. Users may extend the stub freely.
    fn write_hooks(&self, ctx: &AdapterContext) -> CliResult<Option<PathBuf>> {
        let plugins_dir = match ctx.scope {
            InstallScope::Project => ctx.project_root.join(".opencode").join("plugins"),
            InstallScope::User | InstallScope::Global => {
                ctx.home.join(".opencode").join("plugins")
            }
        };
        if !ctx.dry_run {
            std::fs::create_dir_all(&plugins_dir)
                .map_err(|e| crate::error::CliError::io(&plugins_dir, e))?;
        }
        let plugin_path = plugins_dir.join("datatree.ts");
        let body = "// Auto-generated by `datatree install`. Re-run install to refresh.\n\
                    import { execFileSync } from \"node:child_process\";\n\
                    \n\
                    // Safe: execFileSync passes args as a vector, never to a shell.\n\
                    function dt(args: string[]) {\n\
                      execFileSync(\"datatree\", args, { stdio: \"inherit\" });\n\
                    }\n\
                    \n\
                    export default {\n\
                      name: \"datatree\",\n\
                      events: {\n\
                        \"session.created\": (c: any) => dt([\"session-prime\", \"--project\", String(c.cwd), \"--session-id\", String(c.id)]),\n\
                        \"tool.execute.before\": (c: any) => dt([\"pre-tool\", \"--tool\", String(c.tool), \"--params\", JSON.stringify(c.params), \"--session-id\", String(c.session)]),\n\
                        \"tool.execute.after\":  (c: any) => dt([\"post-tool\", \"--tool\", String(c.tool), \"--result-file\", String(c.resultPath), \"--session-id\", String(c.session)]),\n\
                        \"file.edited\":         (c: any) => dt([\"post-tool\", \"--tool\", \"Edit\", \"--result-file\", String(c.path), \"--session-id\", String(c.session)]),\n\
                      },\n\
                    };\n";
        if !ctx.dry_run {
            std::fs::write(&plugin_path, body)
                .map_err(|e| crate::error::CliError::io(&plugin_path, e))?;
        }
        Ok(Some(plugin_path))
    }
}
