//! SST OpenCode adapter.
//!
//! Manifest: `AGENTS.md`
//! MCP: `.opencode.json` `mcpServers`
//! Hooks: `.opencode/plugins/*.ts` (file.edited, session.created, tool.execute.before/after).

use std::path::PathBuf;

use crate::error::CliResult;
use crate::platforms::{
    AdapterContext, InstallScope, McpFormat, Platform, PlatformAdapter,
};

#[derive(Debug, Clone, Copy, Default)]
pub struct OpenCode;

impl PlatformAdapter for OpenCode {
    fn platform(&self) -> Platform {
        Platform::OpenCode
    }

    fn detect(&self, ctx: &AdapterContext) -> bool {
        ctx.project_root.join(".opencode.json").exists()
            || ctx.project_root.join(".opencode").exists()
            || ctx.home.join(".opencode").exists()
    }

    fn manifest_path(&self, ctx: &AdapterContext) -> PathBuf {
        match ctx.scope {
            InstallScope::Project => ctx.project_root.join("AGENTS.md"),
            InstallScope::User | InstallScope::Global => ctx.home.join("AGENTS.md"),
        }
    }

    fn mcp_config_path(&self, ctx: &AdapterContext) -> PathBuf {
        match ctx.scope {
            InstallScope::Project => ctx.project_root.join(".opencode.json"),
            InstallScope::User | InstallScope::Global => ctx.home.join(".opencode.json"),
        }
    }

    fn mcp_format(&self) -> McpFormat {
        McpFormat::JsonObject
    }

    /// Drop a TypeScript plugin stub that wires OpenCode's hook events to
    /// the `mneme` CLI. We use `execFile` (no shell) with array args so
    /// the user's tool/session strings can never be interpreted as shell
    /// metacharacters. Users may extend the stub freely.
    ///
    /// **M1 (audit DEEP-AUDIT-2026-04-29.md §M1):** Honors
    /// `ctx.enable_hooks=false` exactly the way `claude_code.rs:211`
    /// does. Without this gate, `mneme install --no-hooks --platform
    /// opencode` would still write `.opencode/plugins/mneme.ts`,
    /// breaking the K1 contract documented at
    /// `cli/src/platforms/mod.rs:291`.
    fn write_hooks(&self, ctx: &AdapterContext) -> CliResult<Option<PathBuf>> {
        if !ctx.enable_hooks {
            return Ok(None);
        }
        let plugins_dir = match ctx.scope {
            InstallScope::Project => ctx.project_root.join(".opencode").join("plugins"),
            InstallScope::User | InstallScope::Global => {
                ctx.home.join(".opencode").join("plugins")
            }
        };
        if !ctx.dry_run {
            std::fs::create_dir_all(&plugins_dir)
                .map_err(|e| crate::error::CliError::io(&plugins_dir, e))?;
        }
        let plugin_path = plugins_dir.join("mneme.ts");
        // I-1: the absolute path is embedded into the TS template so
        // OpenCode's plugin runtime doesn't depend on `mneme` being on
        // PATH at the time it spawns. JS string-escape: backslashes
        // (Windows paths) are doubled.
        let exe = ctx
            .exe_path
            .to_string_lossy()
            .replace('\\', "\\\\")
            .replace('"', "\\\"");
        let body = format!(
            "// Auto-generated by `mneme install`. Re-run install to refresh.\n\
             import {{ execFileSync }} from \"node:child_process\";\n\
             \n\
             const MNEME_BIN = \"{exe}\";\n\
             \n\
             // Safe: execFileSync passes args as a vector, never to a shell.\n\
             function dt(args: string[]) {{\n\
               execFileSync(MNEME_BIN, args, {{ stdio: \"inherit\" }});\n\
             }}\n\
             \n\
             export default {{\n\
               name: \"mneme\",\n\
               events: {{\n\
                 \"session.created\": (c: any) => dt([\"session-prime\", \"--project\", String(c.cwd), \"--session-id\", String(c.id)]),\n\
                 \"tool.execute.before\": (c: any) => dt([\"pre-tool\", \"--tool\", String(c.tool), \"--params\", JSON.stringify(c.params), \"--session-id\", String(c.session)]),\n\
                 \"tool.execute.after\":  (c: any) => dt([\"post-tool\", \"--tool\", String(c.tool), \"--result-file\", String(c.resultPath), \"--session-id\", String(c.session)]),\n\
                 \"file.edited\":         (c: any) => dt([\"post-tool\", \"--tool\", \"Edit\", \"--result-file\", String(c.path), \"--session-id\", String(c.session)]),\n\
               }},\n\
             }};\n"
        );
        if !ctx.dry_run {
            std::fs::write(&plugin_path, body.as_bytes())
                .map_err(|e| crate::error::CliError::io(&plugin_path, e))?;
        }
        Ok(Some(plugin_path))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    /// M1 (audit DEEP-AUDIT-2026-04-29.md §M1): non-Claude adapters must
    /// honor `ctx.enable_hooks=false` exactly the way `claude_code.rs:211`
    /// does. Without the gate, `mneme install --no-hooks --platform
    /// opencode` would still write `.opencode/plugins/mneme.ts`.
    #[test]
    fn write_hooks_no_op_when_not_enabled() {
        let dir = tempdir().unwrap();
        let mut ctx = AdapterContext::new(InstallScope::User, dir.path().to_path_buf());
        ctx.home = dir.path().to_path_buf();
        assert!(!ctx.enable_hooks, "default must be opt-out");

        let result = OpenCode.write_hooks(&ctx).unwrap();
        assert!(
            result.is_none(),
            "opencode with enable_hooks=false must return Ok(None)"
        );
        let plugin_path = dir
            .path()
            .join(".opencode")
            .join("plugins")
            .join("mneme.ts");
        assert!(
            !plugin_path.exists(),
            "opencode with enable_hooks=false must NOT write {}",
            plugin_path.display()
        );
    }

    #[test]
    fn write_hooks_writes_file_when_enabled() {
        let dir = tempdir().unwrap();
        let mut ctx = AdapterContext::new(InstallScope::User, dir.path().to_path_buf())
            .with_enable_hooks(true);
        ctx.home = dir.path().to_path_buf();

        let result = OpenCode.write_hooks(&ctx).unwrap();
        let plugin_path = dir
            .path()
            .join(".opencode")
            .join("plugins")
            .join("mneme.ts");
        assert_eq!(
            result.as_deref(),
            Some(plugin_path.as_path()),
            "opencode with enable_hooks=true must return the plugin path"
        );
        assert!(
            plugin_path.exists(),
            "opencode with enable_hooks=true must write {}",
            plugin_path.display()
        );
    }
}

